spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    show-sql: true
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

aws:
  s3:
    region: ${AWS_REGION}
    bucket: ${AWS_S3_BUCKET}

logging:
  level:
    com.pacta: DEBUG

pacta:
  mail:
    from: ${MAIL_FROM:no-reply@pacta.app}
  metrics:
    template: "pacta.dev.%s"