-- ─────────────────────────────────────────────────────────────────────────────
-- PACTA — Consolidated schema (final state after V1..V16)
-- Reference only — NOT a Flyway migration. Generated by tracing every
-- ALTER/RENAME/DROP across the existing migrations into one CREATE TABLE
-- per entity, reflecting the current real shape of each table.
-- ─────────────────────────────────────────────────────────────────────────────

-- ── Users ────────────────────────────────────────────────────────────────────
-- V1 create + V5 add city

CREATE TABLE users (
    id               VARCHAR PRIMARY KEY,
    full_name        VARCHAR,
    email            VARCHAR UNIQUE,
    phone_indicative VARCHAR,
    phone_number     VARCHAR,
    country          VARCHAR,
    city             VARCHAR,
    status           VARCHAR,
    score            INTEGER,
    created_at       VARCHAR,
    updated_at       VARCHAR,
    updated_by       VARCHAR,
    removal_reason   VARCHAR,
    removed_at       VARCHAR,
    removed_by       VARCHAR
);

CREATE TABLE user_roles (
    user_id VARCHAR NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role    VARCHAR NOT NULL,
    PRIMARY KEY (user_id, role)
);

-- ── Operators (internal: ADMIN, SUPER_ADMIN, REVIEWER) ──────────────────────
-- V1 create as admin_users + V4 rename to operators, add password_hash

CREATE TABLE operators (
    id            VARCHAR PRIMARY KEY,
    full_name     VARCHAR NOT NULL,
    email         VARCHAR NOT NULL UNIQUE,
    role          VARCHAR NOT NULL,
    status        VARCHAR NOT NULL,
    created_at    VARCHAR NOT NULL,
    updated_at    VARCHAR,
    password_hash VARCHAR
);

-- ── Permissions & RBAC ───────────────────────────────────────────────────────
-- V1, unchanged since

CREATE TABLE permissions (
    id VARCHAR PRIMARY KEY
);

CREATE TABLE role_permissions (
    role       VARCHAR,
    permission VARCHAR,
    PRIMARY KEY (role, permission)
);

-- ── Verification codes (OTP) ─────────────────────────────────────────────────
-- V1, unchanged since

CREATE TABLE verification_codes (
    email      VARCHAR PRIMARY KEY,
    code_hash  VARCHAR,
    expires_at VARCHAR
);

-- ── KYC Documents ────────────────────────────────────────────────────────────
-- V1 create + V2 add reviewed_by/reviewed_at

CREATE TABLE kyc_documents (
    id           VARCHAR PRIMARY KEY,
    user_id      VARCHAR UNIQUE,
    front_key    VARCHAR,
    rear_key     VARCHAR,
    selfie_key   VARCHAR,
    status       VARCHAR,
    submitted_at VARCHAR,
    reviewed_by  VARCHAR,
    reviewed_at  VARCHAR
);

-- ── Document Configs (country-aware compliance doc registry) ────────────────
-- V1 created enum-keyed version, V6 dropped it and replaced with this shape

CREATE TABLE document_configs (
    id           VARCHAR PRIMARY KEY,
    country_code VARCHAR NOT NULL,
    type_code    VARCHAR NOT NULL,
    display_name VARCHAR NOT NULL,
    UNIQUE (country_code, type_code)
);

-- ── Compliance Documents ─────────────────────────────────────────────────────
-- V1 create + V3 add reviewed_by/reviewed_at

CREATE TABLE compliance_documents (
    id            VARCHAR PRIMARY KEY,
    user_id       VARCHAR,
    document_type VARCHAR,
    key           VARCHAR,
    issued_at     VARCHAR,
    expires_at    VARCHAR,
    status        VARCHAR,
    expired       BOOLEAN,
    submitted_at  VARCHAR,
    reviewed_by   VARCHAR,
    reviewed_at   VARCHAR
);

-- ── Bank Accounts ─────────────────────────────────────────────────────────────
-- V1, unchanged since

CREATE TABLE bank_accounts (
    id             VARCHAR PRIMARY KEY,
    user_id        VARCHAR,
    bank_name      VARCHAR,
    account_number VARCHAR,
    account_type   VARCHAR,
    holder_name    VARCHAR,
    created_at     VARCHAR
);

-- ── Properties ───────────────────────────────────────────────────────────────
-- V7 create → V8 rename/retype/add cols → V10 title/address, drop
-- bank_account_id+stratum → V11 add purpose → V12 add country →
-- V14 photo_urls→photo_keys → V15 floor→floors, drop previous_status
--
-- Dropped along the way: bank_account_id, stratum, previous_status (all gone)

CREATE TABLE properties (
    id                  VARCHAR PRIMARY KEY,
    landlord_id         VARCHAR NOT NULL,
    title               VARCHAR,                          -- renamed from `name` (V10)
    purpose             VARCHAR NOT NULL,                  -- V11
    country             VARCHAR(100),                      -- V12
    city                VARCHAR,
    neighborhood        VARCHAR,                           -- V8
    address             VARCHAR,                           -- V10
    type                VARCHAR,
    area                DOUBLE PRECISION,                  -- renamed from area_m2, retyped (V8)
    area_unit           VARCHAR,                           -- V8
    bedrooms            INTEGER,
    bathrooms           INTEGER,
    floors              INTEGER,                           -- renamed from `floor` (V15)
    parking_spots       INTEGER,
    amenities           TEXT,
    photo_keys          TEXT,                              -- renamed from photo_urls (V14)
    description         TEXT,
    monthly_rent        BIGINT,                            -- renamed from monthly_rent_cents (V8)
    currency            VARCHAR,                           -- V8
    admin_fee           BIGINT,                            -- renamed from admin_fee_cents (V8)
    min_contract_months INTEGER,
    allows_pets         BOOLEAN NOT NULL,
    allows_smokers      BOOLEAN NOT NULL,
    allows_children     BOOLEAN NOT NULL,
    status              VARCHAR NOT NULL,
    created_at          VARCHAR NOT NULL,
    updated_at          VARCHAR,
    updated_by          VARCHAR
);

-- ── Property Attribute Configs (admin-managed amenities/services/features) ──
-- V9, unchanged since (V13 only inserted seed rows)

CREATE TABLE property_attribute_configs (
    id            VARCHAR PRIMARY KEY,
    property_type VARCHAR NOT NULL,   -- 'APARTMENT' | 'HOUSE' | 'ROOM' | 'ALL'
    category      VARCHAR NOT NULL,   -- 'AMENITY' | 'SERVICE' | 'FEATURE'
    display_name  VARCHAR NOT NULL,
    enabled       BOOLEAN NOT NULL,
    created_by    VARCHAR NOT NULL,
    created_at    VARCHAR NOT NULL
);

-- ── Property Requests (tenant applications to a property) ───────────────────
-- V16, unchanged since

CREATE TABLE property_requests (
    id          VARCHAR PRIMARY KEY,
    tenant_id   VARCHAR NOT NULL,
    property_id VARCHAR NOT NULL,
    status      VARCHAR NOT NULL,
    applied_at  VARCHAR NOT NULL,
    reviewed_at VARCHAR,
    reviewed_by VARCHAR,
    UNIQUE (tenant_id, property_id)
);
