CREATE TABLE properties (
    id                  VARCHAR PRIMARY KEY,
    landlord_id         VARCHAR NOT NULL,
    bank_account_id     VARCHAR,
    city                VARCHAR,
    type                VARCHAR,
    area_m2             INTEGER,
    bedrooms            INTEGER,
    bathrooms           INTEGER,
    floor               INTEGER,
    stratum             INTEGER,
    parking_spots       INTEGER,
    amenities           TEXT,
    photo_urls          TEXT,
    description         TEXT,
    monthly_rent_cents  BIGINT,
    admin_fee_cents     BIGINT,
    min_contract_months INTEGER,
    allows_pets         BOOLEAN NOT NULL DEFAULT FALSE,
    allows_smokers      BOOLEAN NOT NULL DEFAULT FALSE,
    allows_children     BOOLEAN NOT NULL DEFAULT FALSE,
    status              VARCHAR NOT NULL,
    previous_status     VARCHAR,
    created_at          VARCHAR NOT NULL,
    updated_at          VARCHAR,
    updated_by          VARCHAR
);
